# -*- coding: utf-8 -*-
"""Duration Statistics Module.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aYZOYWpRcbOIe566hOgXFDO5kZri1tDS
"""

#https://pm4py-source.readthedocs.io/en/stable/_modules/pm4py/statistics/traces/generic/log/case_statistics.html

#Dictionary of traces associated to their start timestamp, their end timestamp and their duration
class duration_statistics:


  def cases_description(log):
    from pm4py.statistics.traces.generic.log import case_statistics
    cases_description = case_statistics.get_cases_description(log)
    return cases_description

#Gets all the case durations out of the log
  def all_case_duration(log):
    from pm4py.statistics.traces.generic.log import case_statistics
    return case_statistics.get_all_case_durations(log)



#get_first_quartile_case_duration
  def get_first_quartile_case_duration(log):
    from pm4py.statistics.traces.generic.log import case_statistics
    return  case_statistics.get_first_quartile_case_duration(log)



#    Gets the median case duration out of the log
  def median_case_duration(log): 
    from pm4py.statistics.traces.generic.log import case_statistics
    return case_statistics.get_median_case_duration(log)